//const generateToken = require('../../utils/generateToken')
const db = require('../../../config/db')
const bcrypt = require('bcryptjs')
const Restaurant = require('../../../models/restaurantModel')
const kafka = require('../../../kafka/client')

const handle_request = async (msg, callback) => {
  const { remail, rpassword } = msg
  const restaurant = await Restaurant.findOne({ remail: remail })
  try {
    if (restaurant && (await restaurant.matchPassword(rpassword))) {
      const result = {
        _id: restaurant._id,
        restname: restaurant.restname,
        remail: restaurant.remail,
        //token: generateToken(user._id), // token is generated by using a custom function and jsonwebtoken library. The custom function is available is utils/generatetokens.js
      }
      callback(null, result)
    } else {
      const err = {
        error: "Invalid name/Password'",
      }
      callback(err, null)
    }
  } catch (error) {
    const err = {
      error: 'Internal Server Error',
    }
    callback(err, null)
  }
}

exports.handle_request = handle_request
